### ISSUE TITLE
Files on D:\ not presented properly over FTP

### ISSUE THREAD

**Issue by dracc** [dracc/NevolutionX#50] opened 2020-10-27 19:42 UTC
Prefixed with some numbers and all have the same size - something's fishy.

**Comment by abaire** [comment] 2021-09-17 05:01
Just tested this on my XBOX and cannot reproduce with nxdk at f2c634f and Filezilla 3.52.2 - paths and sizes look correct and match what I see in evox. 

Is it possible that this was due to something fixed in the nxdk?

**Comment by kosmas12** [comment] 2022-02-06 20:50
With xemu using the latest nxdk and Filezilla 3.46.3 (Can't have anything newer right now due to Linux distro repositories) I still have this issue, so it may be worth looking into this.

**Closed** 2022-05-03 00:31 UTC
